openapi: 3.1.0
info:
  title: UCS Unified Content Schema API
  version: 1.0.0
  description: >
    UCS (Unified Content Schema) 是一个面向内容平台聚合的标准协议，提供统一的内容、用户、评论接口。
paths:
  /contents:
    get:
      summary: 查询内容列表
      description: 支持按平台、类型、关键词过滤内容数据
      parameters:
        - name: platform
          in: query
          description: 内容所属平台
          required: true
          schema:
            type: string
        - name: type
          in: query
          description: 内容类型（video/article/note/live）
          required: false
          schema:
            type: string
        - name: keyword
          in: query
          description: 内容关键词搜索
          required: false
          schema:
            type: string
      responses:
        "200":
          description: 查询成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/UCS-Content"
  /contents/{platform}/{content_id}:
    get:
      summary: 获取内容详情
      parameters:
        - name: platform
          in: path
          required: true
          schema:
            type: string
        - name: content_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 获取成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UCS-Content"
  /comments/{platform}/{content_id}:
    get:
      summary: 获取评论列表
      parameters:
        - name: platform
          in: path
          required: true
          schema:
            type: string
        - name: content_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 查询成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UCS-Comment"
  /users/{platform}/{user_id}:
    get:
      summary: 获取用户信息
      parameters:
        - name: platform
          in: path
          required: true
          schema:
            type: string
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 获取成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UCS-User"
components:
  schemas:
    UCS-Content:
      description: 该模块定义了内容的基本信息，支持多种内容类型和详细指标。
      $ref: "../schemas/ucs-content.schema.json"
    UCS-Comment:
      description: 该模块定义了评论的基本信息，支持嵌套评论结构。
      $ref: "../schemas/ucs-comment.schema.json"
    UCS-User:
      description: 该模块定义了用户的基本信息，支持跨平台用户数据的统一表示。
      $ref: "../schemas/ucs-user.schema.json"
